### ISSUE TITLE
character length exceeded - app behaviour issue

### ISSUE THREAD

**Issue by HugoP27** [lutraconsulting/input#1267]
Hi Guys 

I have a field in my geopackage with a max character length of 255, when a user exceeds this they don't get a warning and when they hit 'save' it closes everything and displays a flashing popup of the field contents which can't be closed, example:

![Screenshot_20210315_152855_uk co lutraconsulting](https://user-images.githubusercontent.com/51097011/111163657-f5827e00-85a5-11eb-9a77-6dad39dbfe93.jpg)

I am going to increase the length of the field, but it would be great if the app could warn the user that they have exceeded the max character length by turning red or something, or instead of showing the popup which cant be closed, rather cut off the text at 255 characters or prevent the user from typing beyond that.

**Comment by wonder-sk** [comment]
Generally it's good not to set limits on the lengths of texts unless it is strictly needed - so better to use e.g. TEXT instead of VARCHAR(255) type.

You are right that it would be better not to close the form at the very least and make the error easier to digest. There are unfortunately multiple reasons why this "Value XXX is not compatible with field type YYY" could happen, and not sure yet if we are able to figure out easily what's the underlying reason why it failed...

**Comment by HugoP27** [comment]
Hi @wonder-sk thanks a lot for the suggestion will definitely make my fields text instead of varchar going forward. Old habit of using varchar for text... 🙈

**Comment by saberraz** [comment]
I trust the work-around is good enough.
