### ISSUE TITLE
Confusion with Project and folder names

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#133]
There should be a better way of displaying Projects name under ALL PROJECTS. Currently, it displays folder name and confuses users.

**Comment by sklencar** [comment]
Suggestions:
* Project list of "My Projects" should shown projects by their folder name, similarly to "Mergin projects" list and Mergin itself.
* Downloaded projects will be saved in data folder instead of subfolder "downloads".
* Each project folder will be listed in projects list, but only those can be loaded which contains a single `*.qgs/*.qgz file`.
* If a default project cannot be loaded due to multiple projects file per project folder, the app will ignore default project setup.
