### ISSUE TITLE
Not possible to add decimal numbers in form

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#1395]
- Try to download https://public.cloudmergin.com/projects/lutraconsulting/decimal_issue/tree in Input.
- Add a point and in the form try to add a number in **DBH** field with decimal.

**Comment by sklencar** [comment]
The reported issue seems to be related to precision and setting in the project - DBH field has set 0 precision in the field config. If precision is set to 1+, the widget works. Basically validator blocks any input which is invalid for a field setting and such invalid change is ignored. 

Anyway, there is a bug that invalid value is always in a text field even after reopening the feature form for the same feature (basically wrong synchronisation of a text field and real value of the field, if input was invalid).

The behaviour is inconsistent with QGIS though where a user can write pretty much anything in a text field and then tries to parse it - if its successful, value is changed (considering precision), otherwise ignored. 

Do we want have similar approach?

**Comment by saberraz** [comment]
Best to follow QGIS, so at least there is a consistency.

**Comment by tomasMizera** [comment]
Can we close this one or is it still present?
