### ISSUE TITLE
Multiple selections does not always work

### ISSUE THREAD

**Issue by jarekjj** [lutraconsulting/input#1498]
We have found a small issue with Input App which we cannot resolve. 

Two of the fields in our form have an option for multiple select. Both work fine in QGIS but for some unknown reason one of them doesn't save selections in the Input app. 
You can select multiple options, click Done at the bottom to close the field but when you reopen your selection is not saved. Both fields have the exact same setting in form builder.

Please see the attached video.

I have made the project public on Mergin. It is called Thamesmead_v2, and fields are called Multiple Plant Species (works fine) and Multiple Animal Species (problematic).

https://user-images.githubusercontent.com/13314217/122428939-45e4ef80-cf8a-11eb-8c14-faa40f09f69b.MP4

**Comment by saberraz** [comment]
Reproducible with input-testing/forms_widgets under Relation tab

**Comment by jarekjj** [comment]
Can we have an update on this issue please?

**Comment by sklencar** [comment]
Hi, there is a small bug-fix PR for value relation fields (https://github.com/lutraconsulting/input/pull/1545). However, your problem seems to be related to how value relation values are parsed.

I could replicate the issue with your project **Thamesmead_v3**, having the very same widget configuration for _Multiple Plant Species_ and _Multiple Animal Species_ fields. The difference is that almost all values in the Animal data table has an empty space at the very end of the value (both _Field1_ and _Field2_). Is it intentional?

That white space at the end of a value is trimmed while its parsed from multiple selection (Input uses QGIS core function QgsValueRelationFieldFormatter::valueToStringList). Therefore nothing is set to the field since no value from key column matches trimmed version of the key value.

Note that In the video,  value `Bee - Bumblebee species unidentified` is set as the only one. The value doesn't contain a white space at the end.
