### ISSUE TITLE
Are the linux build docs still valid?

### ISSUE THREAD

**Issue by rduivenvoorde** [lutraconsulting/input#1504]
I thought to try to compile/run input on my Debian/Linux machine, but have some troubles understanding/doing the steps 6 and up from 
https://github.com/lutraconsulting/input/blob/master/docs/developers/linux.md

- I have a self compiled QGIS
- I compiled geodiff succesfully  (both in ~/git/qgis and ~/git/geodiff
- created/edited config.pri in app dir
- but what does 'open input.pro' mean? 
- tried to run 'build/qmake' from menu but failing to go further... 
- fixed a QtMultimedia error with `sudo apt install qtmultimedia5-dev`
- step 7 states: "Add project qgsquick/CMakeLists.txt" to Qt Creator, but I do not have that in my directory
- setting the env vars in 10 in QtCreator it seems Qt cannot find the qgis header files?

```
make: *** [Makefile:3828: attributecontroller.o] Error 1
In file included from ../../qgis/src/core/qgsmaplayerstore.h:24,
                 from ../../qgis/src/core/project/qgsproject.h:43,
                 from ../app/variablesmanager.h:15,
                 from ../app/attributes/attributecontroller.h:35,
                 from ../app/attributes/attributeformmodel.cpp:17:
../../qgis/src/core/qgsmaplayer.h:41:10: fatal error: qgsdataprovider.h: No such file or directory
   41 | #include "qgsdataprovider.h"
```

any help is appreciated

**Comment by tomasMizera** [comment]
Hi @rduivenvoorde!

Linux manual was indeed outdated due to latest changes in qgsquick. Steps 8, 9 and 10 are not needed anymore (`qgsquick` is no longer handled as separate project).

You can find updated `linux.md` here #1509. Note that you will also need to build the https://github.com/nu-book/zxing-cpp lib.

---

> but what does 'open input.pro' mean?

To open input.pro: open qtcreator and navigate to `File > Open File or Project...` and select `input.pro` file. The Input project should then be loaded.

Thanks for the `qtmultimedia5-dev` tip, I have added it also to deps.

Hope that helps, do not hesitate to come back.

**Comment by PeterPetrik** [comment]
@rduivenvoorde please reopen if you still cannot build.
