### ISSUE TITLE
1-N relation using a text field

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#1639]
I am trying to create a 1-N relation using a text field (UUID). It works in QGIS but does not behave well in Input.

**Comment by saberraz** [comment]
https://public.cloudmergin.com/projects/documentation/forms_multiple_photos/tree

**Comment by wonder-sk** [comment]
It looks like that Input is storing fid as the value instead of the value of the column in the relation - the "external-pk" of "photos" layer gets a numeric value instead of uuid. If a photo is added in QGIS, Input shows the link correctly.

There is a similar issue with the reference relation widget - it looks like it expects that the referenced value is a fid (when used with a correct uuid added in qgis, it does not recognize the link - but it "works" fine when feature was added incorrectly in Input).
