### ISSUE TITLE
Map not centring when a feature is identified

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#172]
When I tap on an item and the preview panel pops up, the map does not get centred to the identified feature.

It will be also good to use a different color for showing the identified feature.

**Comment by saberraz** [comment]
This is still an issue for me with the latest release.

Also, identified features don't change color, so user doesn't know which feature is shown in the panel.

**Comment by wonder-sk** [comment]
The map is re-centered only when you click in an area that would otherwise get covered by the preview panel. it works fine for me.

With identified features - currently we draw a small red square on top of the identified point. If your feature is red then it does not show up well... I think we should use different markers for points - e.g. the inverted water drop shape like normally used in web maps.

**Comment by saberraz** [comment]
Ok, the first part works and as you said it only does it for the features covered by preview panel.

I think for the points, it appears below the point and not on top.

It works fine for lines.

**Comment by saberraz** [comment]
Let me close this and open a relevant one.
