### ISSUE TITLE
Support for Oracle provider

### ISSUE THREAD

**Issue by TragicWinter1992** [lutraconsulting/input#1790]
For example when I create a Oracle layer, to my Qgis project and want to upload it to mergin so that the field agents can view for inspection purposes.

The layer tends not to be uploaded.

How can this be fixed.

Kind regards

**Comment by PeterPetrik** [comment]
Hi @TragicWinter1992 , I have moved the issue to input-sdk repository https://github.com/lutraconsulting/input/issues/1790 since it is about packaging. We would need to support Oracle provider in Input App, which means change in QGIS code to support static build of oracle provider and packaging it for iOS and Android (if possible, since it means that the Oracle libraries must be available on the platforms, which I am not 100% they have it). This is not on our foreseeable plan to include (since the common workflow is that you use Geopackage in the field). Where I think it would be better is to support Oracle in db-sync https://github.com/lutraconsulting/mergin-db-sync/issues/59, so you can connect Oracle to Geopackage in the office. If you want to fund the feature please contact info@lutraconsulting.co.uk for quote. Peter
