### ISSUE TITLE
Android 12 and blank white screen for taking photos

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#1904]
When I try to take a photo the camera appears with a blank white screen.

**Comment by tomasMizera** [comment]
Outcome from research:
 - Android 12 gives restriction for using some sensors like OrientationSensor. In order to read it, we need to opt for permission `HIGH_SAMPLING_RATE_SENSORS`. This permission, however, is available only from API 31 ~ Android 12. We have two options, either a) go for it and update to Android 12 (see https://github.com/lutraconsulting/input/pull/1915) or b)  somehow refactor our use of the sensor (e.g. make it unavailable for Android 12+).
 -  If we would go with a) - update to Android 12 - there is an additional issue. I tried to go that path and ended up with this: https://bugreports.qt.io/browse/QTBUG-100437 . It seems that Qt (at least in version that we use) uses old deprecated API for positioning, which Android 12 does not support anymore.

Additional things to try out: 
 - Try to eliminate all EXIF related logic during taking a picture and test if that works on Android 12
 - Disable orientation on Android 12+ and keep target API Android 11

**Comment by tomasMizera** [comment]
New info, (https://bugreports.qt.io/browse/QTBUG-92965) Qt 6.2 implements the new API for positioning.

**Comment by tomasMizera** [comment]
So it seems that it is either update to Android 12 + Qt 6.2 (😨 ) or disable orientation sensor for Android 12+

**Comment by saberraz** [comment]
Let me check this:
- What happens if I take a photo and attach it using the gallery? Does it preserve the exif data...if so, this will be a good enough solution for the time being.
