### ISSUE TITLE
Cant raise info for features

### ISSUE THREAD

**Issue by timlinux** [lutraconsulting/input#234]
Suddenly some of my features are not queryable / editable.

I suspect re-downloading my project is going to fix it, so just adding a recording here to show the issue before I do that:

![forms](https://user-images.githubusercontent.com/178003/55039579-9e7fe900-501c-11e9-8f8b-5f73cfd8d3f4.gif)

Hmm no...even after delete and re-download the project, my elderberry tree is untouchable.

**Comment by wonder-sk** [comment]
Should be fixed when the following QGIS PR is merged and Input is released with latest QGIS master: https://github.com/qgis/QGIS/pull/9637

The problem was that your layer is PointZ but that geometry does not have Z value defined. If you define Z value for that point, things should start to work - as a temporary fix.

**Comment by wonder-sk** [comment]
PR merged, but we will need next version of Input built with latest QGIS master

**Comment by wonder-sk** [comment]
Fixed in 0.2.7
