### ISSUE TITLE
Done is redundant when editing an existing point geometry

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#242]
To reproduce the bug:
1- Open a map with an existing point
2- Click on an existing feature to open the pop up
3- Click on pencil to open the form
4-Press Edit geometry
5- when pressing Done, it says: Recording feature is not valid

Add point works and I think we need to get rid of Done.
![image](https://user-images.githubusercontent.com/2649047/55238945-9945b880-522d-11e9-98ae-16365f83877e.png)

**Comment by saberraz** [comment]
The same actually applies to capturing new geometry. Done just closes the dialog and comes up with an error.

**Comment by wonder-sk** [comment]
if you just start Input, pick a point, go to edit mode, and edit geometry - things work correctly...

But: if you first start recording of "paths" layer, cancel it, then pick a point and do the same as above - it will behave incorrectly (the survey layer bar should not be there, and there should be just three buttons instead of five)

**Comment by saberraz** [comment]
I have tried....and it always results in the above image...with both Add Point and Done
