### ISSUE TITLE
Input does not see all my photos

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#246]
I noticed, if I want to attach a photo (instead of taking one), Input does not list the photos I have recently copied over. But after a while they appear. Does it search for all photos or reads a cache?

**Comment by wonder-sk** [comment]
This seems to be issue with android image selector that after an image is e.g. downloaded in browser or received with whatsapp, the image selector does not immediately show the images - there is a delay. There isn't however probably anything we can do about it since the image selector comes from the OS...
