### ISSUE TITLE
An option to view password while typing

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#543]
when logging into Mergin from Input:
![image](https://user-images.githubusercontent.com/2649047/69957835-7590eb80-14fb-11ea-9fd8-b62a3ed3acb5.png)

**Comment by sklencar** [comment]
This functionality has been added at the some point. (toggle visibility by clicking on the lock icon). Since there is no well-known icon for it, its completely hidden for a user and could be possibly found only by an accident indeed. Suggestion is to change lock icon for an eye icon to save place in field for a small screen devices. 

<img width="625" alt="Screenshot 2019-12-03 at 15 57 09" src="https://user-images.githubusercontent.com/6735606/70062107-b49b6b80-15e5-11ea-82bb-da852f182981.png">

**Comment by saberraz** [comment]
ahhhh....my ignorance!

**Comment by wonder-sk** [comment]
I would still prefer to get this addressed by having an eye icon on the right side, it is hard to figure it out otherwise...
