### ISSUE TITLE
Virtual Fields

### ISSUE THREAD

**Issue by tastrax** [lutraconsulting/input#548]
IOS - It would be good if virtual fields updated on screen rather than on save. For instance if fields 'width and length' are not null then update 'area' virtual field

**Comment by saberraz** [comment]
This is default QGIS behaviour too. I think the rationale behind it is that, otherwise, the software needs to evaluate the expressions and updated fields every time user edits a field. But by pressing OK, it calculates the virtual field.

Maybe we should display something, indicating this will be updated or even the expression...so user is aware of it.

**Comment by tastrax** [comment]
Apologies - didn't realise that it followed QGIS behaviour. I was hoping to show the user the result and then use the calculated value in other calculations. I will have a rethink.

**Comment by she-weeds** [comment]
QGIS can auto-update fields based on other fields using the 'Set default value on update' checkbox. The behaviour is instantaneous in QGIS 3.10 onwards in both the form and attribute table.

Wondering if this could be implemented in Input? For example with a given trunk size, to automatically calculate the protection zone based on a formula (`"trunk_size" * 0.12`) before saving the form.

**Comment by saberraz** [comment]
@she-weeds sure, it should be straight forward. We need to implment it in QGISQuick so that Input can utilise it.

**Comment by saberraz** [comment]
This should be addressed in 0.7.0+ release
