### ISSUE TITLE
Clean up Explore projects

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#702]
The list of public projects is growing. We need to have some method of showing "Featured" projects or other shortlisted method. The rest will be available either by selecting, More... or Search.

**Comment by tastrax** [comment]
Something to consider - the ability to add a description to a project so that folks know what the project actually does and any restrictions on public collecting (ie If I only want records collected in Australia or a specific state). Maybe there could also be some 'templates' which are empty projects that folks can download as samples to then use for their own personal projects (non public)

**Comment by saberraz** [comment]
Great idea...let me file a ticket for description...maybe some "i" icon to appear to the left....

For templates...if you have one (with publicly free and open data), feel free to pass it to me (or point me to it if it s a public project) and I can add it to template in Mergin.

From the Mergin website, when you Create a new project, there is an option to use one as a template:
![image](https://user-images.githubusercontent.com/2649047/82551619-70326680-9b58-11ea-9e76-e2aea7a1dd82.png)

**Comment by tastrax** [comment]
No worries - I will pass on some projects when IOS Input allows projects with one to many relations (ie One trap site with many visits ..... or one weed site with many visits)
