### ISSUE TITLE
Sync creates new "_conflict" geopackage rather than updating main project geopackage.

### ISSUE THREAD

**Issue by urbana-planning** [lutraconsulting/input#709]
I created a project so multiple people can collect land use data in the field, but when at least one person tried to sync their data, the collected data appears to have been saved in a new geopackage with "_conflict" appended to the name of the main geopackage:

![image](https://user-images.githubusercontent.com/17602083/82627169-45d4bd80-9bd9-11ea-954b-984c17602c77.png)
(They synced the data twice, so there are multiple "_conflict" geopackages.)

The data is not syncing for some reason. I am happy that at least it is being saved somewhere, so I can manually sync it later, but this is an issue that I'd like to resolve. It's creating problems for collection, because I have the styles set so that once data is collected, the symbols change color so it's really obvious what has been collected.

When I use Input on my Android phone, there doesn't appear to be an problem syncing the data. The user who is having trouble is using an Android tablet, but I have not been able to take a look at it because we're all working remotely during the COVID-19 pandemic. If there are any suggestions for what I should for if I can get my hands on the problematic tablet, I'm open to hearing them.

**Comment by saberraz** [comment]
Hi @urbana-planning 

Would it be possible to send us the log file from the problematic device. If it is Android, it is located under /sdcard/INPUT/projects/.logs

This happens when the device cannot determine the diff between local and remote survey layer. I suggest to upgrade Input to the latest version (0.6.2 for Android) and see if this continues to happen.

**Comment by wonder-sk** [comment]
I believe this is an instance of the bug https://github.com/lutraconsulting/geodiff/issues/62 which has been fixed in Input version 0.6.4. Please try to upgrade and test again. I will close this ticket now, but in case the problem persists (conflict files get created again), feel free to reopen and we can investigate the issue.
