### ISSUE TITLE
How should file referencing work?

### ISSUE THREAD

**Issue by mostlyAtNight** [lutraconsulting/input#848]
Here's my understanding (please correct me if I'm wrong) of how these settings would affect recording new photos:

![image](https://user-images.githubusercontent.com/884954/92491363-0cf14080-f1ea-11ea-8fc3-c6f01ebb5448.png)

* Default path: This is where new photos will be saved (in this folder). This can be set either using something like `'./photos'` or an expression like `@project_home || '/photos'`
* Relative paths (should be checked, else you'll end up with an attribute value like /SDCARD/bla/bla to a place on the device
* Radio should be for relative from project path so it ends up like `'./photos/my-hilarious-cat.jpeg'`

**Comment by wonder-sk** [comment]
This is also my understanding, with two notes:
- default path is meant to be **absolute** path, so just `./photos` is not going to work (that's why you need an expression with project folder variable)
- relative paths are stored as values without `./` prefix, i.e. it would be just `photos/my-hilarious-cat.jpeg` in your example above

**Comment by wonder-sk** [comment]
See also https://github.com/qgis/QGIS/blob/master/src/quickgui/plugin/editor/qgsquickexternalresource.qml#L28
