### ISSUE TITLE
Crash on Upload of empty files

### ISSUE THREAD

**Issue by charlesangus** [lutraconsulting/input#851]
Uploading from a simple project crashes the app. Restarting Input and trying to upload again results in a popup saying, "Another process is running. Please try again later."

Project has two editable layers, a point layer and a line layer. The point layer has photos attached.

A simpler project with just an editable point layer uploads fine.

**Comment by wonder-sk** [comment]
What platform is it - Android or iOS ? Could you please share the project folder you are trying to sync? Also, there is a hidden file in INPUT/projects/.logs - it would be useful if you could send it as well - there may be some valuable information from the previous failed sync. If your data are private, feel free to send them to me at martin.dobias@lutraconsulting.co.uk

Regarding "Another process is running" message - that happens when server thinks there is a pending upload - here it's before the upload crashed. The project will get unlocked in 5 minutes and it should be possible to sync again.

**Comment by charlesangus** [comment]
This is Android 10. I have sent the project folder and the .logs file to the email specified. Thanks!

**Comment by wonder-sk** [comment]
Thanks for the project folder + logs file. I can confirm a crash on sync which prevents uploads of any changes. The reason is that there are **empty files** which Input wants to push, but crashes before doing that:

```
#4  0x00005555555aace9 in QList<QString>::at(int) const (this=0x7fffffffcbe0, i=0) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qlist.h:544
#5  0x00005555555b1222 in MerginApi::uploadFile(QString const&, QString const&, MerginFile, int)
    (this=0x555555b576d0, projectFullName=..., transactionUUID=..., file=..., chunkNo=0) at ../app/merginapi.cpp:290
#6  0x00005555555bf0b5 in MerginApi::uploadFileReplyFinished() (this=0x555555b576d0) at ../app/merginapi.cpp:1514
```

In `MerginApi::uploadFile()` we try to get the first chunk, but `file.chunks` is actually an empty list which causes the crash.
