### ISSUE TITLE
Project failed to sync.

### ISSUE THREAD

**Issue by HowardEason** [lutraconsulting/input#864]
Traceback (most recent call last):

  File "C:/Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\merginproject.py", line 436, in apply_pull_changes
    self.geodiff.create_changeset(basefile, src, server_diff)

**Comment by wonder-sk** [comment]
Hi @HowardEason - thanks for reporting but unfortunately the error message does not seem to be complete. Are you able to recreate this problem? It would be useful if you could paste the complete error message, ideally also with your project directory so that we can investigate further...

In the future, please file issues related to the Mergin plugin for QGIS in the dedicated repository - https://github.com/lutraconsulting/qgis-mergin-plugin/ - I will eventually move this ticket over there...

**Comment by wonder-sk** [comment]
Following up in https://github.com/lutraconsulting/qgis-mergin-plugin/issues/164
