### ISSUE TITLE
Only one layer appears in Info panel

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#99]
When tapping to view the info, only one layer appears. In my case it is a polygon and blocks all other layers to be identifiable even if I zoom.

**Comment by wonder-sk** [comment]
It is by design that only one feature gets identified.

Hmm it is possible that when user clicks somewhere where there are point/linestring features and polygons as well, a polygon feature "wins" because distance to it is zero, while distance to a point/linestring would be non-zero. Maybe we should enhance the identification logic a bit so we first consider all points/linestrings and only then polygons...

**Comment by wonder-sk** [comment]
fixed in https://github.com/qgis/QGIS/pull/9142
